### ISSUE TITLE
Error: Unable to detect path to vagrant

### ISSUE THREAD

**Issue by wizsilex** [Bipsync/VagrantBar#14]
When i try to start Vagrant Bar it says:
>Vagrant Bar

>Error: Unable to detect path to vagrant

>Install from: http://www.vagrantup.com/

I have installed vagrant from vagrantup.com and not homebrew, current path is:
`which vagrant`       
`/usr/local/bin/vagrant`

**Comment by wizsilex** [comment]
Quick fix: link vagrant to osx bin path
`sudo ln -s /usr/local/bin/vagrant /usr/bin/vagrant`

**Comment by paulatbipsync** [comment]
Fixed in latest
